### ISSUE TITLE
Nikkums.io down?

### ISSUE THREAD

**Issue by fu-raz** [FortuneStreetModding/CustomStreetWorldTour#19]
I just found this mod and all the tools. Seemed to work fine the first time I tried to download the files. But now it just gives me a handshake error in the CSMM app and a 404 in the browser. Did I just get unlucky and did the site go down right after I tried it? Or does the site ban IPs after a first download?

**Comment by nikkiwritescode** [comment]
Hello @fu-raz, and thank you for reporting the issue! I've been working on this issue for a little while, and I was able to reproduce the problem exactly as you described. It turned out that Microsoft Azure had some _really, really old_ DNS records for the domain that were being picked up periodically. So while it is too soon to know for sure, I have reason to believe this issue is permanently resolved.

I'm going to leave this issue open for the next week. If in that time you're continuing to see the problem, please let me know. If I don't hear anything, I'll close the issue at that time.

Thank you again for reporting the issue! 🎉

**Comment by fu-raz** [comment]
I thought it was a bandwidth limiting thing, because when I connected via VPN it all started working again. Old DNS records makes a lot more sense. I've been able to download everything without any issues since, so I think this issue is resolved!

Thanks for the response and also for the work you've done.
